### ISSUE TITLE
Will model.models be released in the future

### ISSUE THREAD

**Issue by FengxinLee** [Data-Designer/COAST#1]
Hi, I have taken notice of your work since released on arxiv. It's an interesting work. I was curious if there are any plans to release the models in the future?

**Comment by Data-Designer** [comment]
yes

**Comment by FengxinLee** [comment]
Hello, sorry to disturb you. I have read the latest codes and have some trouble understanding the training process of *GraphNet_NGCF* .

It appears that the function *get_douban_graph* creates instance of *GraphNet_NGCF* , but it only returns the embeddings and neighbor table. The GCN network does not seem to be used during the training process, and there is no optimizer for the GCN network. Is it the case that GCN network does not require training and is only utilized to initialize the embeddings?

**Comment by Data-Designer** [comment]
Yes! Here, we don't let the GCN handle the updates directly. Instead, we utilize it to initialize the embeddings.

I recall attempting to incorporate it into the update process, but it didn't yield favorable results.




| |
赵闯
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 6/9/2023 16:51 |
| To | ***@***.***> |
| Cc | Data ***@***.***> ,
State ***@***.***> |
| Subject | Re: [Data-Designer/COAST] Will model.models be released in the future (Issue #1) |

Hello, sorry to disturb you. I have read the latest codes and have some trouble understanding the training process of GraphNet_NGCF .

It appears that the function get_douban_graph creates instance of GraphNet_NGCF , but it only returns the embeddings and neighbor table. The GCN network does not seem to be used during the training process, and there is no optimizer for the GCN network. Is it the case that GCN network does not require training and is only utilized to initialize the embeddings?

**Comment by FengxinLee** [comment]
Thank you for your response. It seems that the parameters of GCN network is randomly initialized, and would it be more effective to use a non-parameter GCN network, such as LightGCN?

**Comment by Data-Designer** [comment]
Yes!
In our subsequent tests, we discovered that using methods that don't require the Laplacian matrix, such as GAT (Graph Attention Network), yielded better results.
| |
赵闯
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 6/9/2023 17:06 |
| To | ***@***.***> |
| Cc | Data ***@***.***> ,
State ***@***.***> |
| Subject | Re: [Data-Designer/COAST] Will model.models be released in the future (Issue #1) |

Thank you for your response. It seems that the parameters of GCN network is randomly initialized, and would it be more effective to use a non-parameter GCN network, such as LightGCN?

**Comment by FengxinLee** [comment]
Get it. Thanks for your sharing.
